"""Add Application and HiddenFile models

Revision ID: 036a60255b28
Revises: a64d44ea23ff
Create Date: 2025-09-27 11:03:51.373316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036a60255b28'
down_revision = 'a64d44ea23ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('icon', sa.String(length=200), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('isLocked', sa.Boolean(), nullable=False),
    sa.Column('lastUsed', sa.DateTime(), nullable=True),
    sa.Column('usageTime', sa.Integer(), nullable=True),
    sa.Column('schedule_enabled', sa.Boolean(), nullable=True),
    sa.Column('schedule_startTime', sa.String(length=5), nullable=True),
    sa.Column('schedule_endTime', sa.String(length=5), nullable=True),
    sa.Column('schedule_days', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hidden_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('encrypted', sa.Boolean(), nullable=True),
    sa.Column('folder', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hidden_files')
    op.drop_table('applications')
    # ### end Alembic commands ###
